name: Lint Code

on:
    pull_request:
        paths:
            - '**/*.py'
        branches: [master]
    push:
        paths:
            - '**/*.py'
        branches: [master]
    
    workflow_dispatch:


jobs:
    pylint:
        name: Lint Python Code
        runs-on: ubuntu-20.04
        container: python:2.7.18-buster

        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pylint
            - name: Run pylint and ensure a perfect score
              run: 'find . -name "*.py" | xargs pylint --msg-template="{path}({line}): [{obj}] {msg} ({symbol})"'
