name: Automated Tests

on: [pull_request, workflow_dispatch]
      
jobs:
  test:
    runs-on: ubuntu-20.04
    container: python:2.7.18-buster

    steps:
        # Checkout the latest code from the repo
      - name: Checkout repo
        uses: actions/checkout@v2
        # Display the Python version being used
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        # Install pytest
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
        # Run the tests. I'm using pytest and the file is in the tests directory.
      - name: Check Files
        run: find ./tests -type f -name "*.py" | python -m pytest -s -rfsE -p no:cacheprovider